#!/bin/bash
echo "hello good morinig"
echo "welcome to my session"
echo "hello good morinig"
echo "welcome to my session"
echo "hello good morinig"
echo "welcome to my session"
echo "hello good morinig"
echo "welcome to my session"
echo "hello good morinig"
echo "welcome to my session"
echo "hello good morinig"
echo "welcome to my session"
